[project]
name = "vmcrawl"
version = "0.4"
description = "Mastodon-focused version reporting crawler"
requires-python = ">=3.13"

dependencies = [
    "psycopg[binary]",
    "httpx[http2]",
    "beautifulsoup4",
    "python-dotenv",
    "toml",
    "lxml",
    "packaging",
]