[project]
name = "vmcrawl"
version = "0.2"
description = "Mastodon-focused version reporting crawler"
requires-python = ">=3.12"

dependencies = [
    "dnspython",
    "httpx[http2]",
    "beautifulsoup4",
    "python-dotenv",
    "toml",
    "lxml",
]